# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greentext < Formula
  desc "A CLI tool for creating green-text memes"
  homepage "https://github.com/jasonuc/greentext"
  version "1.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jasonuc/greentext/releases/download/v1.1.2/greentext_1.1.2_Darwin_x86_64"
      sha256 "983938c10680436caeca7b93d94a8e3c120a44c855de3c5c057c503738297518"

      def install
        bin.install "greentext_1.1.2_Darwin_x86_64" => "greentext"
      end
    end
    on_arm do
      url "https://github.com/jasonuc/greentext/releases/download/v1.1.2/greentext_1.1.2_Darwin_arm64"
      sha256 "deaf657b6715d9cfafabe38f20025b26f323914716e91a001a6a959866a513a2"

      def install
        bin.install "greentext_1.1.2_Darwin_arm64" => "greentext"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jasonuc/greentext/releases/download/v1.1.2/greentext_1.1.2_Linux_x86_64"
        sha256 "2fa9dfcd62844722a9fdfa6ddebe494010c03bfb791a18e05b89959bde1d9017"

        def install
          bin.install "greentext_1.1.2_Linux_x86_64" => "greentext"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jasonuc/greentext/releases/download/v1.1.2/greentext_1.1.2_Linux_arm64"
        sha256 "a3d4fad1e0f80f502101c80c96224228c40dc27c9f47646ae8ecd6457b23cede"

        def install
          bin.install "greentext_1.1.2_Linux_arm64" => "greentext"
        end
      end
    end
  end
end
