# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greentext < Formula
  desc "A CLI tool for creating green-text memes"
  homepage "https://github.com/jasonuc/greentext"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jasonuc/greentext/releases/download/v1.2.0/greentext_1.2.0_Darwin_amd64_1734210676"
      sha256 "1bfb8084392224b0e5c6bde7601ad73e5f1c5dab97f0ad6ff2a9125cb03f5ab2"

      def install
        bin.install "greentext_1.2.0_Darwin_amd64_1734210676" => "greentext"
      end
    end
    on_arm do
      url "https://github.com/jasonuc/greentext/releases/download/v1.2.0/greentext_1.2.0_Darwin_arm64_1734210676"
      sha256 "b5c7c2ad6e89ad79993b4a5be47b89816b8070a7d90ded860a4b1dd715a8334d"

      def install
        bin.install "greentext_1.2.0_Darwin_arm64_1734210676" => "greentext"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jasonuc/greentext/releases/download/v1.2.0/greentext_1.2.0_Linux_amd64_1734210676"
        sha256 "03254aa6f32dd73f022ffe5d51b8b7d153375c9b2d34f0a7ea78037395d5f199"

        def install
          bin.install "greentext_1.2.0_Linux_amd64_1734210676" => "greentext"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jasonuc/greentext/releases/download/v1.2.0/greentext_1.2.0_Linux_arm64_1734210676"
        sha256 "d09e05b5f6be9971d9fca9c19efb318cb514d1bc7aad0ab9113ed0afb7dce941"

        def install
          bin.install "greentext_1.2.0_Linux_arm64_1734210676" => "greentext"
        end
      end
    end
  end
end
