# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greentext < Formula
  desc "A CLI tool for creating green-text memes"
  homepage "https://github.com/jasonuc/greentext"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jasonuc/greentext/releases/download/v1.3.0/greentext_1.3.0_Darwin_amd64_1740514507"
      sha256 "a152a518fdcb8ede18cf684088e4c50dd1ba82e7eeae3c995c87dfaf1d229481"

      def install
        bin.install "greentext_1.3.0_Darwin_amd64_1740514507" => "greentext"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jasonuc/greentext/releases/download/v1.3.0/greentext_1.3.0_Darwin_arm64_1740514507"
      sha256 "6685bce4ab27a804a2c03998efc449ea4c9708c7b77f58b8da9518ad86435dbd"

      def install
        bin.install "greentext_1.3.0_Darwin_arm64_1740514507" => "greentext"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jasonuc/greentext/releases/download/v1.3.0/greentext_1.3.0_Linux_amd64_1740514507"
        sha256 "c3561f71f2364ab19153aaa2043a9ce66545b0093b8d2ec74cebc2e7090201a9"

        def install
          bin.install "greentext_1.3.0_Linux_amd64_1740514507" => "greentext"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jasonuc/greentext/releases/download/v1.3.0/greentext_1.3.0_Linux_arm64_1740514507"
        sha256 "55c3c62b2ccd9cd4e45f983f7f0485266427b260baeda2f954933fdd05e9bc3f"

        def install
          bin.install "greentext_1.3.0_Linux_arm64_1740514507" => "greentext"
        end
      end
    end
  end
end
